### ISSUE TITLE
[idea] API to allow libary users to add and support their own tags

### ISSUE THREAD

**Issue by djgilcrease** [google/rpmpack#29]
Currently `rpmpack` must maintain a full list of tags and values itself so every time a library needs to support a tag that is not currently in rpmpack they must make a PR here and then update their use after the PR is accepted. So I am proposing reworking the API a bit to make it easier for those using rpmpack as a library to add support for the tags they need without rpmpack explicitly knowing about or _officially_ supporting it.

**Rough API Idea**
```go
func (r *RPM) AddTag(rpmTag int, value IndexEntry) {...}
func (r *RPM) AddSignatureTag(rpmTag int, value IndexEntry) {...}
func NewIndexEntry(value interface{}) IndexEntry {...}
```

**Comment by jarondl** [comment]
I like this idea, and the API seems mostly reasonable.
I am somewhat weary of the third function though: Would it panic in runtime if value's type is not something we recognize? Perhaps we should return an error? Or perhaps we should provide one method for each type we know about?
