### ISSUE TITLE
comparators ("senses") bitmasks in relations are not mapped correctly

### ISSUE THREAD

**Issue by rbtr** [google/rpmpack#31]
It looks like the comparators (`<`, `>`, `=`) are not mapped correctly to their rpm bitmask representations:
Example input (through goreleaser/nfpm):
```
- "dep"
- "dep < 2.0.0"
- "dep > 1.0.0"
- "dep = 1.5.0" 
- "dep <= 1.6.0"
- "dep >= 1.4.0"
```
Result:
```
$ rpm -qpR dist/test.rpm
dep
dep  2.0.0
dep < 1.0.0
dep > 1.5.0
dep > 1.6.0
dep <> 1.4.0
```

According to the [RPM source](https://github.com/rpm-software-management/rpm/blob/master/lib/rpmds.h#L26-L29) the correct bitmasks are (with my => decimal calculation):
```
RPMSENSE_ANY = 0, // => 0
RPMSENSE_LESS = (1 << 1), // => 2
RPMSENSE_GREATER = (1 << 2), // => 4
RPMSENSE_EQUAL = (1 << 3), // => 8
```

However the [`rpmpack` bitmasks](https://github.com/google/rpmpack/blob/master/sense.go#L15-L20) are:
```
SENSE_ANY = 1 << iota >> 1, // iota == 0 so => 0
SENSE_LESS // 1 << 1 >> 1 => 1
SENSE_GREATER // 1 << 2 >> 1 => 2
SENSE_EQUAL // 1 << 3 >> 1 => 4
```

it looks to me like overcomplicating the bitshift `iota` has caused the shifts to be off.

---
I have tested and verified that adjusting the "sense" bitshifts results in a correct rpm:
```
SenseAny  rpmSense = 0
SenseLess          = 1 << iota
SenseGreater
SenseEqua
```

Result: 
```
dep 0
dep 2 2.0.0
dep 4 1.0.0
dep 8 1.5.0
dep 10 1.6.0
dep 12 1.4.0
...
$ rpm -qpR dist/test.rpm
dep 
dep < 2.0.0
dep > 1.0.0
dep = 1.5.0
dep <= 1.6.0
dep >= 1.4.0
```

**Comment by rbtr** [comment]
I checked the rest of the codebase for this shift pattern and the usage [here](https://github.com/google/rpmpack/blob/master/file_types.go#L11) looks okay, but according to the doc linked in that header, the `0` value is `RPMFILE_NONE`, not a "generic" file?

**Comment by djgilcrease** [comment]
`RPMFILE_NONE` is the default an Generic made more sense to me as a name.

**Comment by rbtr** [comment]
It reads to me like that is a special flag indicating "no file", not a "generic file", but I have not read enough of the RPM sourcecode to say for sure
