### ISSUE TITLE
Owner and Group seem reversed

### ISSUE THREAD

**Issue by WeirdBob** [google/rpmpack#40]
Hi,

is this inversion wanted or a typo (rpm.go l.375):
```
	r.fileowners = append(r.fileowners, f.Group)
	r.filegroups = append(r.filegroups, f.Owner)
```

Trying to create an RPM with rpmpack and then read it with go-rpmutils, the owner and group are switched

**Comment by jarondl** [comment]
I've just checked, and all of my own rpms have "root:root" so I did not catch this typo :)

@WeirdBob Are you able and willing to write some unittests and code to fix this? If not I can do this, but I cannot guarantee a timeframe.

**Comment by WeirdBob** [comment]
Hi @jarondl 
I submitted a merge request. I didn't find the unit tests for RPM struct so I put mine in a new rpm_test.go file. It only covers the code I modified.
Let me know if you prefer it somewhere else or if you have comments.
Happy to help.
