### ISSUE TITLE
tar2rpm: rpm -ivh of generated .rpm fails with cpio: Digest mismatch

### ISSUE THREAD

**Issue by steffenbusch** [google/rpmpack#49]
I have generated a valid, functioning TAR file with Apache Ant (file says: POSIX tar archive). 
When I create an RPM file with tar2rpm there are neither errors or warnings reported but when the generated .rpm file should be installed with "rpm -ivh" the installation fails with:

**error: unpacking of archive failed** on file /redhat-release;5f2712a5: **cpio: Digest mismatch**
error: Example-0:1.0-.noarch: install failed

# Steps to reprodude:

Use this Dockerfile:

```
FROM oraclelinux:7

RUN yum -y install oracle-golang-release-el7
RUN yum -y install golang git ant file

RUN go get -u github.com/google/rpmpack/...

RUN echo "<project name='test' default='main' basedir='.'>" >/tmp/build.xml && \
    echo "  <target name='main'>" >>/tmp/build.xml && \
    echo "    <tar destfile='/tmp/generated-by-ant.tar'>" >>/tmp/build.xml  && \
    echo "      <tarfileset dir='/etc' username='root' group='root'>" >>/tmp/build.xml && \
    echo "        <include name='redhat-release'/>" >>/tmp/build.xml && \
    echo "      </tarfileset>" >>/tmp/build.xml && \
    echo "    </tar>" >>/tmp/build.xml && \
    echo "  </target>" >>/tmp/build.xml&& \
    echo "</project>" >> /tmp/build.xml

RUN ant -f /tmp/build.xml
 
ENTRYPOINT ["bash"]
```

Build and run:

```
docker build -t rpmtest .
docker run --rm -it rpmtest
```

Run these commands in the Docker Container:

```
# Run file to determine the file type:
file /tmp/generated-by-ant.tar
# List the contents of the tar file (or extract it, it will work)
tar -tvf /tmp/generated-by-ant.tar
# Run the tar2rpm tool to generate the rpm
/root/go/bin/tar2rpm -file /tmp/example.rpm -name "Example" -version "1.0" --build_time "$(date +%s)" /tmp/generated-by-ant.tar

#Try to install the rpm
rpm -ivh /tmp/example.rpm
```

The last command will produce this error:

```
[root@e5a144d2b99f /]# rpm -ivh /tmp/example.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:Example-0:1.0-                   ################################# [100%]
error: unpacking of archive failed on file /redhat-release;5f2712a5: cpio: Digest mismatch
error: Example-0:1.0-.noarch: install failed
[root@e5a144d2b99f /]# 
```

**Comment by jarondl** [comment]
Interesting... The tar seems fine. Also running `rpm2cpio` worked. But the digest data in the rpm is wrong:

```
# rpm -ql --dump -p /tmp/example.rpm 
/redhat-release 52 1585757277 0000000000000000000000000000000000000000000000000000000000000000 0100644 root root 0 0 1 Red Hat Enterprise Linux Server release 7.8 (Maipo)
```
I would be really surprised if the md5sum of your file is 000..

Also, why is `Red Hat Enterprise Linux Server release 7.8 (Maipo)` in this output?  According to http://ftp.rpm.org/max-rpm/s1-rpm-query-parts.html#S3-RPM-QUERY-L-OPTION this should only happen for a symlink...  Wait is this a symlink??

For some reason rpm thinks this is a symlink. What does the tar say? the file in the tar has permissions `0100644`. My working example has `0000644`.
 Oh NO....
https://github.com/google/rpmpack/blob/3685799e8fdfbe44568b34614dc25b9fb544b3a2/rpm.go#L397
`0100644 & 0120000 == 0100000 != 0`.

That is clearly a bug in rpmpack, should not be too difficult to fix.

**Comment by jarondl** [comment]
Thank you for the reproducible bug report. Can you check if #50 solves the issue?

**Comment by steffenbusch** [comment]
Thanks a lot @jarondl 
I have cloned your repo, build tar2rpm and performed a **successful test** with my own, out of Apache Ant generated, production TAR file. The cpio: Digest mismatch is gone and the .rpm, generated with tar2rpm, was successfully installed without further issues.
