### ISSUE TITLE
Ghost files are not properly supported in the RPM - file is still installed when installing the package

### ISSUE THREAD

**Issue by wwade** [google/rpmpack#51]
With reference to [Maximum RPM]:

> ### The %ghost Directive
>
> As we mentioned in the Section called The %files List, if a file is specified in the %files list, that file will automatically be included in the package. There are times when a file should be owned by the package but not installed - log files and state files are good examples of cases you might desire this to happen.
> 
> The way to achieve this, is to use the %ghost directive. By adding this directive to the line containing a file, RPM will know about the ghosted file, but will not add it to the package.

The examples there go on to show common RPM operations.  Essentially, what needs to happen is that the file is _owned_ by the RPM, but no file contents are added to the same.

The file should be:
1. Shown in `rpm -qlp <package.rpm`
2. Shown as provided-by the rpm `rpm -q --whatprovides <my-ghost-file>`
3. Not present in the filesystem after installing the package.

1 & 2 are currently achieved, but 3 is not correct. We end up with an empty file, instead.

[Maximum RPM]: http://ftp.rpm.org/max-rpm/s1-rpm-inside-files-list-directives.html

**Comment by jarondl** [comment]
Huh. So the file is indexed, but not installed. Does that mean it appears in all of the rpm data structures (`dirindexes`, `dirnames`, `filesizes`) but not in the cpio archive? If so we can easily fix this by expanding the switch in https://github.com/google/rpmpack/blob/1c1eea4553328679d2228b8ada67e6f91fce81c3/rpm.go#L412-L429 to handle ghost files specially without calling writePayload.

But first I have to be sure that this is how RPM implements this. RPM is full of surprises, so let's check it out first.

**Comment by wwade** [comment]
Thanks for having a look. Yeah, I confirmed it out with an `rpmbuild` RPM using `%ghost` and then `rpm2cpio | cpio` to extract the contents - the file was not present.

    % rpm2cpio ghastly.noarch.rpm | cpio --list --verbose
    1 block
    % rpm2cpio normal.rpm | cpio --list
    ./etc/config.json
    1 block
    %

One thing, though: when I _installed_ the RPM, it did create all the leading directory components for the file, just not the file itself, so it seems that the directory part of the record (if that's the correct notion) still exists.

**Comment by jarondl** [comment]
Hi, can you check if #52 solves your issue?

**Comment by wwade** [comment]
> Hi, can you check if #52 solves your issue?

Yes, looks great, thanks so much!
