### ISSUE TITLE
xz, lzma compression don't work

### ISSUE THREAD

**Issue by mharvey-jt** [google/rpmpack#61]
for `xz`, `lzma` but not `gzip` compression types, the  output rpms are apparently corrupt:
```
rpmsample | rpm2cpio | cpio -t
cpio: premature end of archive
```

tested with rpm2cpio from rhel7 and upstream 4.16.1.3

**Comment by jarondl** [comment]
@djgilcrease - as the contributor of xz and lzma to rpmpack (#19) do you want to take a stab at this?

**Comment by djgilcrease** [comment]
Sure, will take a look at it today.

**Comment by djgilcrease** [comment]
this appears to be an issue specific to rhel7 I tested this with Fedora34, centos 8, centos 7 and I am not seeing this issue.

**Comment by djgilcrease** [comment]
I would guess that rhel7 only really supports gzip based on https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-package-structure.html#id674921

> According to the LSB standards, the RPMTAG_PAYLOADFORMAT must always be cpio. The RPMTAG_PAYLOADCOMPRESSOR must be gzip. The RPMTAG_PAYLOADFLAGS must always be 9.

**Comment by mharvey-jt** [comment]
Ok, makes sense.  Thanks for investigating, let's close this now.

**Comment by jarondl** [comment]
Thank you @mharvey-jt for reporting, and thank you so much @djgilcrease  for finding the reason!

Without doubt, rpm is the gift that keeps on giving. I think we'll treat this closed bug as documentation, if anyone else complains we may need to put something in the readme as well.
