### ISSUE TITLE
No prefix support for generated rpm

### ISSUE THREAD

**Issue by entropaos** [google/rpmpack#79]
Hello, team, this project looks not support prefix for the rpm package. So the rpm package is not relocatable. Guys, is there a plan to support this feature?

**Comment by jarondl** [comment]
We have no problem to support it, but someone needs to a bit of digging.

I suspect it would be rather easy - set a string array tag with the tag value of `RPMTAG_INSTPREFIXES`, and with the prefixes.

I can check if its as simple as that.

**Comment by jarondl** [comment]
It was not `RPMTAG_INSTPREFIXES` but rather `RPMTAG_PREFIXES`, but I think I got this to work.
